Add support for hadolint config

diff --git a/run b/run
--- a/run
+++ b/run
@@ -4,7 +4,19 @@ set -u
 
 config=$(cat -)
 file=$(echo "$config" | jq -r '."source"')
+resources=$(echo "$config" | jq -r '."resources"')
 language=$(echo "$config" | jq -r '."natural_language"')
+
+hadolint_args=""
+
+for filename in .hadolint.yml .hadolint.yaml hadolint.yml hadolint.yaml
+do
+  filename="$resources/$filename"
+  if [ -f "$filename" ]; then
+    hadolint_args="--config=$filename"
+    break
+  fi
+done
 
 if [ "$language" = "nl" ]; then
   title="Gerenderd"
@@ -23,7 +35,7 @@ echo "{\"command\": \"start-tab\", \"title\": \"$title\"}"
 
 if [ -s "$file" ]; then
   fail="$(mktemp)"
-  if { hadolint --format json "$file" || echo > "$fail"; } |
+  if { hadolint $hadolint_args --format json "$file" || echo > "$fail"; } |
      jq '.[] | .column -= 1 | .command = "annotate-code" | .row = .line - 1 | .text = .message | .type = if .level == "style" or .level == "ignore" then "info" else .level end | del(.code, .file, .line, .level, .message)' \
     && [ -s "$fail" ]
   then
